version: 2

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - qtbase5-dev
    - xvfb
